name: aws-web-deployment
description: Deploy a React app to AWS S3 and CloudFront using the AWS CDK
author: Sigatoka Engineering
inputs:
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region where the S3 bucket and CloudFront distribution will be created. Default: us-east-1'
  build-directory:
    description: 'Absolute path to the directory containing your static site bundle'
  domain-name:
    description: 'The name of the S3 bucket where the React app will be uploaded'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
